### PR TITLE
Add missing #include <stddef.h> to atca_iface.h

### PR DESCRIPTION
**Pull request by akindestam**
Needed for size_t

### CODE REVIEW

**Comment by akindestam** [comment]
I haven't checked if the same error is in any other file.

This include error was long masked in our project, but a reordering of includes in one of the projects files unmasked it.

**Comment by bryan-hunt** [comment]
This is an internal header. One should always include cryptoauthlib.h

**Comment by akindestam** [comment]
> This is an internal header. One should always include cryptoauthlib.h

We are including cryptoauthlib.h, but this issue is still happening.
Do you mean to say that cryptoauthlib.h should always be included first? Or cryptoauthlib.h solely?
In our project we sort includes alphabetically, so the cryptoauthlib.h include can end up being included later. It might've been the case that we've included some internal header directly that wasn't strictly neccessary though (or was neccessary in an earlier version of cryptoauthlib)

Either way, even for an internal header it could be argued it is better style to always include the pertinent headers, rather than relying on other headers including them for you (this header was already including stdlib.h)

**Comment by akindestam** [comment]
Seems we were including `atca_cfgs.h` before `cryptoauthlib.h`. Removing that makes it compile. Despite that, I still feel `stddef.h` not being included here is an oversight.

**Comment by bryan-hunt** [comment]
Release v3.3.2 included this header file.

**Pull request closed without merging**
