### PR TITLE
Bug fix for atca_mbedtls_cert_add (issue #109)

### PR DESCRIPTION
**Pull request by zynaptic**
This PR fixes the bug detailed in issue #109 where atcacert_read_cert is called without correctly initialising the cert_len parameter.
The PR also removes some unused variable declarations which were causing compilation warnings when using the PIC32MZ2048EF I2C HAL.

### CODE REVIEW

**Comment by AdityaHPatwardhan** [comment]
I also face this issue which is fixed with this PR, when using `cryptoauthlib` with esp32, I get error `BUFFER_TO_SMALL` when calling `mbedtls_cert_add` function, please help to merge this PR.

**Comment by zynaptic** [comment]
This PR is now out of date with respect to the main repo, but I've had a quick look at the latest code and the bug is still present.

**Comment by bryan-hunt** [comment]
Release v3.2.1 should have resolved this PR

**Comment by zynaptic** [comment]
I've not had chance to test v3.2.1 in my builds, but the change is simple enough that I think it's safe to close the PR. Thanks for adding the fix.

**Pull request closed without merging**
