### PR TITLE
Update atcacert_host_sw.c

### PR DESCRIPTION
**Pull request by vincentthivent**
# Please describe the purpose of this pull request

Change size of signature

# Checklist
* [x] I have reviewed the [CONTRIBUTING.md](https://github.com/MicrochipTech/cryptoauthlib/blob/main/CONTRIBUTING.md) and agree to it's terms

### CODE REVIEW

**Comment by vincentthivent** [comment]
Change size of signature

**Comment by vincentthivent** [comment]
Change size of signature
ret = atcac_pk_verify(&pkey_ctx, challenge, 32, response, 64);

**Comment by Srinivas-E** [comment]
Hi @vincentthivent ,
Thanks for sharing your feedback. We will consider this change in our upcoming release.

**Comment by vincentthivent** [comment]
Thanks @Srinivas-E  👍

**Pull request closed without merging**
